// Warning: this file was generated from src/LinAlg/MatFwdTemplate.h.  Do not edit if you value your changes!

#ifndef LINALG_MAT2_FWD_H
#define LINALG_MAT2_FWD_H

namespace LinAlg {
    template <typename T> class Mat2;
    
    /// A float matrix
    typedef Mat2<float> Mat2f;
    
    /// A double matrix
    typedef Mat2<double> Mat2d;
    
    /// A int matrix
    typedef Mat2<int> Mat2i;
    
    /// An unsigned int matrix
    typedef Mat2<unsigned> Mat2u;
}

#endif
