// Warning: this file was generated from src/LinAlg/MatFwdTemplate.h.  Do not edit if you value your changes!

#ifndef LINALG_MAT3_FWD_H
#define LINALG_MAT3_FWD_H

namespace LinAlg {
    template <typename T> class Mat3;
    
    /// A float matrix
    typedef Mat3<float> Mat3f;
    
    /// A double matrix
    typedef Mat3<double> Mat3d;
    
    /// A int matrix
    typedef Mat3<int> Mat3i;
    
    /// An unsigned int matrix
    typedef Mat3<unsigned> Mat3u;
}

#endif
