// Warning: this file was generated from src/LinAlg/MatFwdTemplate.h.  Do not edit if you value your changes!

#ifndef LINALG_MAT4_FWD_H
#define LINALG_MAT4_FWD_H

namespace LinAlg {
    template <typename T> class Mat4;
    
    /// A float matrix
    typedef Mat4<float> Mat4f;
    
    /// A double matrix
    typedef Mat4<double> Mat4d;
    
    /// A int matrix
    typedef Mat4<int> Mat4i;
    
    /// An unsigned int matrix
    typedef Mat4<unsigned> Mat4u;
}

#endif
