// Warning: this file was generated from src/LinAlg/VecFwdTemplate.h.  Do not edit if you value your changes!

#ifndef LINALG_VEC2_FWD_H
#define LINALG_VEC2_FWD_H

namespace LinAlg {
    template <typename T> class Vec2;

    /// A float vector
    typedef Vec2<float> Vec2f;
    
    /// A double vector
    typedef Vec2<double> Vec2d;
    
    /// A int vector
    typedef Vec2<int> Vec2i;
    
    /// An unsigned int vector
    typedef Vec2<unsigned> Vec2u;
}

#endif
