// Warning: this file was generated from src/LinAlg/VecFwdTemplate.h.  Do not edit if you value your changes!

#ifndef LINALG_VEC3_FWD_H
#define LINALG_VEC3_FWD_H

namespace LinAlg {
    template <typename T> class Vec3;

    /// A float vector
    typedef Vec3<float> Vec3f;
    
    /// A double vector
    typedef Vec3<double> Vec3d;
    
    /// A int vector
    typedef Vec3<int> Vec3i;
    
    /// An unsigned int vector
    typedef Vec3<unsigned> Vec3u;
}

#endif
