// Warning: this file was generated from src/LinAlg/VecFwdTemplate.h.  Do not edit if you value your changes!

#ifndef LINALG_VEC4_FWD_H
#define LINALG_VEC4_FWD_H

namespace LinAlg {
    template <typename T> class Vec4;

    /// A float vector
    typedef Vec4<float> Vec4f;
    
    /// A double vector
    typedef Vec4<double> Vec4d;
    
    /// A int vector
    typedef Vec4<int> Vec4i;
    
    /// An unsigned int vector
    typedef Vec4<unsigned> Vec4u;
}

#endif
