LinAlg: LinAlg::Transform3< T > Class Template Reference
LinAlg::Transform3< T > Class Template Reference
A 3D affine transformation represented as a 4x4 matrix.
#include <Transform3.h>
Public Member Functions
Transform3 ()
The identity transform.
Transform3 (const Mat4< T > &values)
Initialize from a matrix of values.
Transform3 (const Mat3< T > &R, const Vec3< T > &t)
Initialize from a rotation/scaling matrix and a translation vector.
Transform3 (const Transform3 &other)
Copy an affine transform.
Transform3 & operator= (const Transform3 &other)
Assign an affine transform to this one.
T getScale () const
Return the uniform scaling factor.
T getScaleSqr () const
Return the uniform scaling factor squared.
Vec3< T > getTranslation () const
Return the translation.
Transform3 inverse () const
Calculate the inverse of the transfromation.
Vec3< T > transPoint (const Vec3< T > &v) const
Transform a point.
Vec3< T > transVector (const Vec3< T > &v) const
Transform a vector.
Public Member Functions inherited from LinAlg::Mat4< T >
Mat4 ()
Create an uninitialized matrix.
Mat4 (const T v00, const T v10, const T v20, const T v30, const T v01, const T v11, const T v21, const T v31, const T v02, const T v12, const T v22, const T v32, const T v03, const T v13, const T v23, const T v33)
Create a matrix from named values.
template<typename Other >
Mat4 (const Mat4< Other > &m)
Copy another matrix of possibly a different type.
Mat4 & operator= (const Mat4 &m)
Assign another matrix to this matrix.
const T & operator() (const unsigned i, const unsigned j) const
Read-only element access.
T & operator() (const unsigned i, const unsigned j)
Read-write element access.
const T * data () const
Direct read-only access to the underlying m_data.
T * data ()
Direct read-write access to the underlying m_data.
const_iterator begin () const
Get a read-only iterator to the first element.
iterator begin ()
Get a read-write pointer to the first element.
const_iterator end () const
Get a read-only iterator to past the last element.
iterator end ()
Get a read-write iterator to past the last element.
unsigned size1 () const
The number of rows.
unsigned size2 () const
The number of columns.
void limit (const std::pair< T, T > &l)
Limit each element to the range [l.first, l.second].
void limit (const T lower, const T upper)
Limit each element to the range [lower, upper].
void limit (const Mat4 &lower, const Mat4 &upper)
Limit element (i,j) to the range [lower(i,j), upper(i,j)].
T sum () const
Return the sum of all the elements.
T prod () const
Return the product of all the elements.
Mat4 trans () const
Return the transpose of this matrix.
Vec4< T > getCol (const unsigned i) const
Get the i'th column of the matrix.
void setCol (const unsigned i, const Vec4< T > &v)
Set the i'th column of the matrix.
Vec4< T > getRow (const unsigned i) const
Get the i'th row of the matrix.
void setRow (const unsigned i, const Vec4< T > &v)
Set the i'th row of the matrix.
void eigs (Vec4< T > &values, Mat4 &vectors) const
Compute the eigenvalues and eigenvectors.
bool equal (const Mat4< T > &v, const T eps) const
Compare entries with another matrix, within eps.
Mat4 & operator+= (const Mat4 &m)
Add another matrix to this one.
Mat4 & operator-= (const Mat4 &m)
Subtract another matrix from this one.
Mat4 & operator*= (const T d)
Multiply this matrix by a scalar value.
Mat4 & operator/= (const T d)
Divided this matrix by a scalar value.
Static Public Member Functions
Various affine transforms creators.
static Mat4< T > identity ()
Return the identity transform.
static Mat4< T > translation (const Vec3< T > &v)
Return a translation transform.
static Mat4< T > scale (const T &s)
Return a uniform scaling transform.
static Mat4< T > rotation (const T angle, const Vec3< T > &v)
Return a rotation transform of angle radians about the unit vector axis.
static Mat4< T > rotation (const Vec3< T > &axisAngle)
Return a rotation transform of axis.length() radians about the unit vector in the direction of axis.
Static Public Member Functions inherited from LinAlg::Mat4< T >
static const Mat4 & zero ()
Return the zero matrix.
static const Mat4 & ident ()
Return the identity matrix.
static Mat4 inverse (const Vec4< T > &values, const Mat4 &vectors)
Calculate the inverse of a matrix from its eigenvalues and eigenvectors.
static std::string description ()
Return a description like "2D float", useful for debugging and messages.
Additional Inherited Members
Public Types inherited from LinAlg::Mat4< T >
enum { num_dims = 4 }
The number of dimensions.
enum { num_elements = 4 * 4 }
The number of elements.
typedef Mat4< T > self_type
This type.
typedef Vec4< T > vec_type
The vector type of the same dimension.
typedef T value_type
The underlying data type.
typedef T * iterator
An iterator.
typedef const T * const_iterator
A constant iterator.
Protected Attributes inherited from LinAlg::Mat4< T >
T m_data [4 *4]
The element storage.
Detailed Description
template<typename T>
class LinAlg::Transform3< T >
A 3D affine transformation represented as a 4x4 matrix.
This version supports translation, rotation, and uniform scales.
Member Function Documentation
template<typename T> static Mat4<T> LinAlg::Transform3< T >::rotation (const T angle, const Vec3< T > & v) inline static
Return a rotation transform of angle radians about the unit vector axis.
Note
This clearly won't work very well for integer types T.
Referenced by LinAlg::Transform3< T >::rotation().
template<typename T> static Mat4<T> LinAlg::Transform3< T >::rotation (const Vec3< T > & axisAngle) inline static
Return a rotation transform of axis.length() radians about the unit vector in the direction of axis.
Note
This clearly won't work very well for integer types T.
References LinAlg::Vec3< T >::length(), and LinAlg::Transform3< T >::rotation().
The documentation for this class was generated from the following file:
Transform3.h
© 2005-2008 Adrian Secord.